### ISSUE TITLE
Verify API are usable

### ISSUE THREAD

**Issue by calippo** [buildo/mailo#2]
Check with someone other than myself that Mailo APIs are nice and usable.

**Comment by gabro** [comment]
First pass, after offline discussion: the API makes sense and it's easy to use.

The abstraction of MailData and HttpClient is leaky, but it's not a big concern for now.
Let's focus on getting this in place on our projects and we'll potentially talk about a better abstraction in the future.

I'll review the code more thoroughly over the next week.
