### ISSUE TITLE
configure mailgun timezone to UTC

### ISSUE THREAD

**Issue by lucacioria** [buildo/mailo#26]
## requirements
- as a developer
- I want mailgun accounts to use UTC
- to avoid confusion about datetimes of emails when debugging
## specs

{optional: describe technical specs to implement this feature, if not obvious}
## misc

track backporting cross project:
- [x] hailadoc
- [x] lexDo.it
- [x] OXWAY

**Comment by calippo** [comment]
Done, also mailgun staging is UTC now

**Comment by lucacioria** [comment]
not clear what you mean, also not clear if you backported it to all projects

**Comment by calippo** [comment]
I backported it to all projects. Also old emails are now UTC.
1 mailgun account was missing in your list. We have an account for mailo-testing.
Backported also for mailo-testing account.
