### ISSUE TITLE
Test that emails with images are rendered correctly

### ISSUE THREAD

**Issue by calippo** [buildo/mailo#4]
A template should be allowed to include images (for instance for the logo).

**Comment by lucacioria** [comment]
Image support is already available as it's just an HTML tag, and the image can be hosted on s3. I don't think this issue is relevant for the scope of this project.

**Comment by calippo** [comment]
This will probably take less than 5 minutes: just test and see if there's a convenient way to deal with images (#3 will probably take less time than this ^^).

**Comment by lucacioria** [comment]
@calippo maybe I wasn't clear, but this is **not related** to mailo. It's part of the design of the template, it's done in an external tool, and for mailo it'll only be html as everything else.

**Comment by gabro** [comment]
Offline discussion with claudio: this is just a reminder that templates with images are rendered correctly.

No extra work is needed to support images.

**Comment by calippo** [comment]
Email with image rendered correctly
![screen shot 2016-04-20 at 13 23 15](https://cloud.githubusercontent.com/assets/2476080/14672908/1697868c-06fb-11e6-82d0-9809120616e6.png)
